# Generated by Django 2.1.7 on 2019-03-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('surname', models.CharField(max_length=55, verbose_name='Surname')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=55, verbose_name='Line name')),
            ],
            options={
                'verbose_name': 'Production line',
                'verbose_name_plural': 'Production lines',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=55, verbose_name='Customer')),
                ('project_number', models.PositiveSmallIntegerField(verbose_name='Project number')),
                ('dead_line', models.DateField(verbose_name='Dead line')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('project_status', models.CharField(choices=[('Preparation', 'Preparation'), ('In progress', 'In progress'), ('Done', 'Done')], default='Preparation', max_length=12)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=5, verbose_name='Shortcut')),
                ('description', models.TextField(verbose_name='Description')),
                ('done', models.PositiveSmallIntegerField(default=0, verbose_name='Done')),
                ('efficiency', models.PositiveSmallIntegerField(default=0, verbose_name='Min for piece')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_app.Projects')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.AddField(
            model_name='productionline',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.Work'),
        ),
        migrations.AddField(
            model_name='employees',
            name='production_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.ProductionLine'),
        ),
    ]
