# Generated by Django 2.1.7 on 2019-03-27 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Name')),
                ('surname', models.CharField(max_length=55, verbose_name='Surname')),
                ('salary', models.PositiveSmallIntegerField(verbose_name='Salary(zł/h)')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Expenses')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price', models.FloatField(verbose_name='Price for piece')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=55, verbose_name='Customer')),
                ('project_number', models.CharField(max_length=33, unique=True, verbose_name='Project number')),
                ('dead_line', models.DateField(verbose_name='Dead line')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('project_status', models.CharField(choices=[('Preparation', 'Preparation'), ('In progress', 'In progress'), ('Done', 'Done')], default='Preparation', max_length=12)),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Global project cost')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Raports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(verbose_name='Time')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Made pieces')),
                ('date', models.DateField(default=datetime.datetime(2019, 3, 27, 16, 10, 22, 449372), verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Raport',
                'verbose_name_plural': 'Raports',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=5, verbose_name='Shortcut')),
                ('description', models.TextField(verbose_name='Description')),
                ('done', models.PositiveSmallIntegerField(default=0, verbose_name='Done')),
                ('efficiency', models.FloatField(default=0, verbose_name='Min for piece')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_app.Projects')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='WorkerProductivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(verbose_name='Time in hours')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Made pieces')),
                ('average_productivity', models.FloatField(verbose_name='Average productivity')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.Work')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.Employees')),
            ],
            options={
                'verbose_name': 'Worker productivity',
                'verbose_name_plural': 'Workers productivity',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='worker_productivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.WorkerProductivity'),
        ),
        migrations.AddField(
            model_name='raports',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.Work'),
        ),
        migrations.AddField(
            model_name='raports',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.Employees'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_app.Projects'),
        ),
    ]
